services:
  - type: web
    name: gift-shop-backend
    env: python
    region: oregon
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main

